# Generated by Django 5.0.4 on 2024-05-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.CharField(max_length=255)),
                ('answer_uz', models.CharField(max_length=255)),
                ('question_en', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_en', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_list', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Requirement List',
                'verbose_name_plural': 'Requirements List',
                'db_table': 'requirements_list',
            },
        ),
        migrations.CreateModel(
            name='RequirementsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_title', models.CharField(max_length=255)),
                ('req_description', models.TextField()),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tuit.requirements')),
            ],
            options={
                'verbose_name': 'Requirement Information',
                'verbose_name_plural': 'Requirements Information',
                'db_table': 'requirements_information',
            },
        ),
    ]
