# Generated by Django 5.0.4 on 2024-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publications/')),
                ('description_uz', models.CharField(max_length=255)),
                ('description_en', models.CharField(max_length=255)),
                ('file_uz', models.FileField(upload_to='publications/')),
                ('file_en', models.FileField(upload_to='publications/')),
                ('category', models.ManyToManyField(related_name='publications', to='app_tuit.categories')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
            },
        ),
    ]
