# Generated by Django 5.0.4 on 2024-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0002_categories_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publications',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='publications/'),
        ),
    ]
