# Generated by Django 5.0.4 on 2024-05-19 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0005_papersinformation_reviewers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewers',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='reviewers',
            name='reviewer',
            field=models.ManyToManyField(related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
