# Generated by Django 5.0.4 on 2024-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0006_remove_reviewers_reviewer_reviewers_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersinformation',
            name='file_en',
            field=models.FileField(blank=True, null=True, upload_to='papers/en'),
        ),
        migrations.AlterField(
            model_name='papersinformation',
            name='file_uz',
            field=models.FileField(upload_to='papers/uz'),
        ),
    ]
