# Generated by Django 5.0.4 on 2024-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0007_alter_papersinformation_file_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Send Email',
                'verbose_name_plural': 'Send Emails',
                'db_table': 'send_email',
            },
        ),
    ]
