# Generated by Django 5.0.4 on 2024-05-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0010_reviewers_first_name_reviewers_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewers',
            old_name='file',
            new_name='review_file',
        ),
        migrations.RenameField(
            model_name='reviewers',
            old_name='review',
            new_name='review_text',
        ),
    ]
