# Generated by Django 5.0.4 on 2024-05-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tuit', '0011_rename_file_reviewers_review_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersinformation',
            name='papers',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_tuit.papers'),
            preserve_default=False,
        ),
    ]
